
version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    image: selimhorri/service-discovery-ecommerce-boot:dev
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
  cloud-config-container:
    image: selimhorri/cloud-config-ecommerce-boot:dev
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
  api-gateway-container:
    image: selimhorri/api-gateway-ecommerce-boot:dev
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
      - cloud-config-container
  order-service-container:
    image: selimhorri/order-service-ecommerce-boot:dev
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - api-gateway-container
  payment-service-container:
    image: selimhorri/payment-service-ecommerce-boot:dev
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - api-gateway-container
  product-service-container:
    image: selimhorri/product-service-ecommerce-boot:dev
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - api-gateway-container
  shipping-service-container:
    image: selimhorri/shipping-service-ecommerce-boot:dev
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - api-gateway-container
  user-service-container:
    image: selimhorri/user-service-ecommerce-boot:dev
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - api-gateway-container
  favourite-service-container:
    image: selimhorri/favourite-service-ecommerce-boot:dev
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin-container:9411/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery-container:8761/eureka
      - EUREKA_INSTANCE=service-discovery-container
    depends_on:
      - service-discovery-container
      - cloud-config-container
      - api-gateway-container



