
server:
  servlet:
    context-path: /user-service

spring:
  zipkin:
    base-url: http://localhost:9411/
  config:
    import: optional:configserver:http://localhost:9296
  application:
    name: USER-SERVICE
  profiles:
    active:
    - dev
  jackson:
    serialization:
      indent-output: true

